# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 01:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donaciones_monetarias',
            name='Cantidad',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='donadores',
            name='Donador_tel',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Ingrese un numero de telefono valido', regex='^[0-9|\\-]*$')]),
        ),
    ]
