# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0002_auto_20161122_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento_apoyo',
            name='Donacion_especie',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='seguimiento_apoyo',
            name='Donacion_monetaria',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8),
        ),
    ]
