# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 03:56
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admon_nombre', models.CharField(max_length=40)),
                ('Admon_tel', models.CharField(max_length=15)),
                ('Admon_correo', models.EmailField(max_length=254)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Defunciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_apoyo', models.DateField(default=datetime.date.today)),
                ('Apoyo', models.IntegerField()),
                ('Recipiente_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Donaciones_Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(default=datetime.date.today)),
                ('Descripcion', models.CharField(max_length=60)),
                ('Unidades', models.CharField(max_length=20)),
                ('Cantidad', models.IntegerField()),
                ('Donador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Donadores')),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_evento', models.DateField()),
                ('Lugar_evento', models.CharField(max_length=100)),
                ('Hora_evento', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Minutas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_reunion', models.DateField()),
                ('Total_donacionesmon', models.IntegerField()),
                ('Valor_donacionesesp', models.IntegerField()),
                ('Duracion_reunion', models.CharField(max_length=15)),
                ('Pacientes_beneficiados', models.IntegerField()),
                ('Observaciones', models.TextField()),
                ('Asistentes', models.ManyToManyField(to='home.Administradores')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paciente_nombre', models.CharField(max_length=40)),
                ('Paciente_apellido', models.CharField(max_length=50)),
                ('Paciente_fnacimiento', models.DateField()),
                ('Paciente_diagnostico', models.CharField(max_length=200)),
                ('Paciente_clinica', models.CharField(max_length=50)),
                ('Tutor_Padre', models.CharField(max_length=50)),
                ('Paciente_contacto', models.CharField(blank=True, max_length=15)),
                ('Estado_salud', models.CharField(choices=[('RE', 'Remision'), ('TR', 'En Tratamiento'), ('DEP', 'Fallecido')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Personal_nombre', models.CharField(max_length=40)),
                ('Personal_apellidos', models.CharField(max_length=50)),
                ('Personal_funcion', models.CharField(max_length=60)),
                ('Personal_tel', models.CharField(max_length=15)),
                ('Personal_correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento_Apoyo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_entrega', models.DateField(default=datetime.date.today)),
                ('Apoyo_Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Paciente')),
                ('Donacion_especie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.Donaciones_Especie')),
            ],
        ),
        migrations.AlterField(
            model_name='donaciones_monetarias',
            name='Fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='donaciones_monetarias',
            name='Forma_pago',
            field=models.CharField(choices=[('CH', 'Cheque'), ('DE', 'Deposito'), ('EF', 'Efectivo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='historial_medico',
            name='Fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='historial_medico',
            name='Paciente_hm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Paciente'),
        ),
        migrations.DeleteModel(
            name='Pacientes',
        ),
        migrations.AddField(
            model_name='seguimiento_apoyo',
            name='Donacion_monetaria',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.Donaciones_Monetarias'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='Personal_evento',
            field=models.ManyToManyField(to='home.Personal'),
        ),
        migrations.AddField(
            model_name='defunciones',
            name='Paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Paciente'),
        ),
    ]
