# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 07:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admon_nombre', models.CharField(max_length=40)),
                ('Admon_tel', models.CharField(max_length=15)),
                ('Admon_correo', models.EmailField(max_length=254)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('editar', 'Edicion de registros'), ('crear_admin', 'Crear administradores'), ('asig_permisos', 'Asignar permisos')),
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_evento', models.CharField(max_length=30)),
                ('Fecha_evento', models.DateField()),
                ('Lugar_evento', models.CharField(max_length=100)),
                ('Hora_evento', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Minutas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_reunion', models.DateField()),
                ('Total_donacionesmon', models.IntegerField()),
                ('Valor_donacionesesp', models.IntegerField()),
                ('Duracion_reunion', models.CharField(max_length=15)),
                ('Pacientes_beneficiados', models.IntegerField()),
                ('Observaciones', models.TextField()),
                ('Asistentes', models.ManyToManyField(to='Admon.Administradores')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Personal_nombre', models.CharField(max_length=40)),
                ('Personal_apellidos', models.CharField(max_length=50)),
                ('Personal_funcion', models.CharField(max_length=60)),
                ('Personal_tel', models.CharField(max_length=15)),
                ('Personal_correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='eventos',
            name='Personal_evento',
            field=models.ManyToManyField(to='Admon.Personal'),
        ),
    ]
