# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 01:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradores',
            name='Admon_nombre',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='Valor invalido', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='Admon_tel',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Ingrese un numero de telefono valido', regex='^[0-9|\\-]*$')]),
        ),
        migrations.AlterField(
            model_name='minutas',
            name='Total_donacionesmon',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='minutas',
            name='Valor_donacionesesp',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Personal_apellidos',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Valor invalido', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Personal_nombre',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='Valor invalido', regex='^[a-zA-Z]*$')]),
        ),
    ]
